routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\QuizzController;
use App\Http\Controllers\QuestionController;
use Illuminate\Routing\Route as RoutingRoute;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    'register'=>false,
    'reset'=>false,
    'verify'=>false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('start/quizz/{quizz}',[ExamController::class,'startQuizz'])->name('quizz.enter');
Route::post('/result/create',[ExamController::class,'register']);
Route::get('/result/user/{user}/quizz/{quizz}',[ExamController::class,'showresult'])->name('show.result');
Route::group(['middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.index');
    });
    Route::resource('quizz', QuizzController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('user', UserController::class);
    Route::get('/exam/create',[ExamController::class,'create']);
    Route::get('/exam',[ExamController::class,'index']);
    Route::get('/exam/quizz/{quizz}',[ExamController::class,'questions'])->name('exam.question');
    Route::post('/exam/create',[ExamController::class,'store'])->name('exam.store');
    Route::post('/exam/remove',[ExamController::class,'remove'])->name('exam.remove');

});

app/Models/Quizz.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Question;
use Illuminate\Http\Client\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Quizz extends Model
{
    use HasFactory;

    protected $fillable=['name','desc','minutes'];

    public function questions()
    {
        return $this->hasMany(Question::class);
 

    }
    public function users()
    {
      return $this->belongsToMany(User::class,'quizz_users','quizz_id','user_id');
    }
    public function createQuizz($data)
        {
          return  Quizz::create($data);
        }
        public function attemptQuizz()
    {
        $attemptquizz=[];
        $authuser=auth()->user()->id;
      $resultuser=Result::where('user_id',$authuser)->get();
      foreach($resultuser as $user ){
        array_push($attemptquizz,$user->quizz_id);
      }
      return $attemptquizz;

      } 
}

app/Http/Controllers/QuizzController.php
<?php

namespace App\Http\Controllers;

use App\Models\Quizz;
use Illuminate\Http\Request;

class QuizzController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.quizz.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('backend.quizz.quizz');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$this->validateQuizz($request);

        $quizz= (new Quizz)->createQuizz($data);

        return back()      
            ->with('success',"Successfully added!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Quizz $quizz)

    {
       return view('backend.quizz.edit',compact('quizz'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Quizz $quizz)
    {
        $data=$this->validateQuizz($request);
            $quizz->update($data);

            return back()->with('success',"update Successful");
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Quizz $quizz)
    {
        $quizz->delete();
        return back()->with('error','Delete successul!');
    }
    public function validateQuizz($request)
    {
     return  $this->validate($request,[
        'name'=> 'required|string|max:25',
        'desc'=> 'required|string|max:255',
        'minutes'=> 'required|integer|max:25',
       ]);
    }
}

resources/views/backend/quizz/edit.blade.php
@extends('backend.master')

@section('content')
@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <a href="{{route('quizz.index')}}" class="btn btn-success float-right">All List</a>
        <div class="module">
            <div class="module-name">
                <h3>Edit Quizz</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('quizz.update',[$quizz->id])}}"  method="POST">
                    @csrf 
                    @method('put')

                <div class="control-group">
                    <label for="">Quizz</label>
                    <div class="controls">
                    <input type="text" name="name" class="span8" value="{{$quizz->name}}">
                    </div>

                    @error('name')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    

                    <label for="">Description</label>
                    <div class="controls">
                        <input type="text" name="desc" class="span8" value="{{$quizz->desc}}" />
                    </div>
                    @error('desc')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">Minutes</label>
                    <div class="controls">
                        <input type="number" name="minutes" class="span8"value="{{$quizz->minutes}}"">
                    </div>
                    @error('minutes')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <input type="submit" class="btn btn-success" value="Update"/>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection
@endsection

resources/views/backend/quizz/index.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    
    @if (Session::has('error'))
    <div class="alert alert-danger">
        
        {{Session::get('error')}}</div>

    @endif
    <div class="module">
        <div class="module-title">
           <h3>All Quizz</h3>
        </div>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Description</th>
                <th>Minutes</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse (App\Models\Quizz::latest()->get() as $key=>$item)
                <tr>
                <td>{{$key+1}}</td>
                <td>{{$item->name}}</td>
                <td>{{$item->desc}}</td>
                <td>{{$item->minutes}}</td>

                <td>{{$item->created_at}}</td>
                <td>{{$item->updated_at}}</td>
                <td>
                <a href="{{route('quizz.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
                <form action="{{route('quizz.destroy',[$item->id])}}" method="POST">
                    @csrf
                    @method('delete')
                    <td>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </td>  
                </form>
            </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6">There are no quizz yet.</td>                    
                </tr>
                
            @endforelse
        </tbody>
    </table>
</div>
</div>

@endsection

resources/views/backend/quizz/quizz.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Register Quizz</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('quizz.store')}}"  method="POST">
                    @csrf 

                <div class="control-group">
                    <label for="">Quizz</label>
                    <div class="controls">
                        <input type="text" name="name" class="span8" placeholder="Please enter quizz">
                    </div>

                    @error('name')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    

                    <label for="">Description</label>
                    <div class="controls">
                        <input type="text" name="desc" class="span8" placeholder="Please enter quizz" />
                    </div>
                    @error('desc')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">Minutes</label>
                    <div class="controls">
                        <input type="number" name="minutes" class="span8" placeholder="Please enter quizz">
                    </div>
                    @error('minutes')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <input type="submit" class="btn btn-success">Register</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection