routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\QuizzController;
use App\Http\Controllers\QuestionController;
use Illuminate\Routing\Route as RoutingRoute;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    'register'=>false,
    'reset'=>false,
    'verify'=>false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('start/quizz/{quizz}',[ExamController::class,'startQuizz'])->name('quizz.enter');
Route::post('/result/create',[ExamController::class,'register']);
Route::get('/result/user/{user}/quizz/{quizz}',[ExamController::class,'showresult'])->name('show.result');
Route::group(['middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.index');
    });
    Route::resource('quizz', QuizzController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('user', UserController::class);
    Route::get('/exam/create',[ExamController::class,'create']);
    Route::get('/exam',[ExamController::class,'index']);
    Route::get('/exam/quizz/{quizz}',[ExamController::class,'questions'])->name('exam.question');
    Route::post('/exam/create',[ExamController::class,'store'])->name('exam.store');
    Route::post('/exam/remove',[ExamController::class,'remove'])->name('exam.remove');

});

app/Models/Question.php
<?php

namespace App\Models;

use App\Models\Quizz;
use App\Models\Answer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Question extends Model
{
    use HasFactory;

    protected $fillable=['question','quizz_id'];

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function quizz()
    {
        return $this->hasOne(Quizz::class,'id','quizz_id');
    }
    public function storeQuestion($data)        
    {
        return Question::create([
            'question'=>$data['question'],
            'quizz_id'=>$data['quizz_id']

        ]);
    }
    public function getQuestion()
    {
        return Question::latest()
                        ->with("quizz")
                        ->paginate(2);


                    }
                   

}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;
use Mockery\Matcher\Any;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions=(new Question)->getQuestion();
        // return $questions;
       return view('backend.question.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.question.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$this->validatQuestion($request);
        // dd($data);
        $storequestion=(new Question)->storeQuestion($data);
        $storeanswer=(new Answer)->storeAnswer($data,$storequestion);

        return back()
                ->with('success',"Questions are registered!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        return view('backend.question.edit',compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Question $question)
    {
        $data=$this->validatQuestion($request);
        $storequestion=$question->update($data);
       Answer::where('question_id',$question->id)->delete();

       $storeanswer=(new Answer)->storeAnswer($data,$question);

        // $updateAnswer=(new Answer)->deleteAnswer($question->id);
    //    $updateanswer= $question->answers->update($data);
        // foreach($data->options as $key=>$answer){
            
        // }
        // $storeanswer=(new Answer)->storeAnswer($data,$updatequestion);
        // $storeanswer=(new Answer)->storeAnswer($data,$updatequestion);

       return back()
            ->with('success',"Infromations are updated!");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
       $question->delete();

       return back()->with('error',"Quizz is delted");
    }
    public function validatQuestion($request)
    {
            return $this->validate($request,[
                'question'=>'required|string|max:30' ,
                'quizz_id'=>'required',
                'options'=>'required|array|min:3',
                'options.*'=>'required|string|distinct',
                'correct_answer'=>'required'
            ]);
    }

}

resources/views/backend/question/create.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Register Question To the Quizz</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('question.store')}}"  method="POST">
                    @csrf 

                <div class="control-group">
                    <label for="">Choose Quizz</label>
                    <div class="controls">
                       <select name="quizz_id" id="" class="span8">
                            @foreach (App\Models\Quizz::all() as $item)
                       <option value="{{$item->id}}">{{$item->name}}</option>  
                            @endforeach

                       </select>
                    </div>

                    @error('quizz_id')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">Question</label>
                    <div class="controls">
                        <input type="text" name="question" class="span8" placeholder="Please enter quizz">
                    </div>
                  
                    @error('question')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    
                    <label for="">Answers</label>
                    <div class="controls">
                        @for ($i = 0; $i < 4; $i++)
                        <input type="text" name="options[]" class="span6" placeholder="Please type  answer.">
                    <input type="radio" name="correct_answer" value="{{$i}}"> This is a correct answer.
                    
                    @endfor
                    </div>
                    @error('options.*')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    @error('correct_answer')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                   
                

                    
                    <button type="submit" class="btn btn-success"> Submit</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/question/edit.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Edit Question To the Quizz</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('question.update',[$question->id])}}"  method="POST">
                    @csrf 
                    @method('put')

                <div class="control-group">
                    <label for="">Choose Quizz</label>
                    <div class="controls">
                       <select name="quizz_id" id="" class="span8">
                            @foreach (App\Models\Quizz::all() as $item)
                       <option value="{{$item->id}}" @if($question->quizz->id==$item->id) selected @endif>{{$item->name}}</option>  
                            @endforeach

                       </select>
                    </div>

                    @error('quizz_id')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">Question</label>
                    <div class="controls">
                    <input type="text" name="question" class="span8" value="{{$question->question}}">
                    </div>
                  
                    @error('question')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    
                    <label for="">Answers</label>
                    <div class="controls">
                        @foreach($question->answers as $key=>$answer)
                    <input type="text" name="options[]" class="span6" value="{{$answer->answer}}">
                    <input type="radio" name="correct_answer" value="{{$key}}" @if($answer->is_correct==1) checked @endif> This is a correct answer.
                    
                    @endforeach
                    </div>
                    @error('options.*')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    @error('correct_answer')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                   
                

                    
                    <button type="submit" class="btn btn-success"> Submit</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/question/index.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('error'))
        <div class="alert alert-danger">
            
            {{Session::get('error')}}</div>

        @endif
        @foreach ($questions as $key=>$item)
        <div class="module">
            <div class="module-title">
                <h3>{{ $item->quizz->name}}</h3>
                <h4>{{ $item->quizz->desc}}</h4>
                <h4>{{ $item->question}}</h4>
              <div class="module-body">
              <p>Given Minutes-{{$item->quizz->minutes}}</p>
              @foreach ($item->answers as $answer)
                  <p>{{$answer->answer}}
                    @if ($answer->is_correct==1)
                    <input type="checkbox" checked> <span class="badge badge-success">Correct Answer</span>
                    @else
                    <input type="checkbox" >
                    @endif
                </p>
              @endforeach
            </div> 

       
            <a href="{{route('question.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
        <form action="{{route('question.destroy',[$item->id])}}" method="POST">
            @csrf
            @method('delete')

            <button type="submit" class="btn btn-danger">delete</button>
        </form>    
        </div>
        </div>
        @endforeach
       
            
    </div>
    <div class="pagination">
        {{ $questions->links() }}

    </div>

</div>

@endsection