routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\QuizzController;
use App\Http\Controllers\QuestionController;
use Illuminate\Routing\Route as RoutingRoute;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    'register'=>false,
    'reset'=>false,
    'verify'=>false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('start/quizz/{quizz}',[ExamController::class,'startQuizz'])->name('quizz.enter');
Route::post('/result/create',[ExamController::class,'register']);
Route::get('/result/user/{user}/quizz/{quizz}',[ExamController::class,'showresult'])->name('show.result');
Route::group(['middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.index');
    });
    Route::resource('quizz', QuizzController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('user', UserController::class);
    Route::get('/exam/create',[ExamController::class,'create']);
    Route::get('/exam',[ExamController::class,'index']);
    Route::get('/exam/quizz/{quizz}',[ExamController::class,'questions'])->name('exam.question');
    Route::post('/exam/create',[ExamController::class,'store'])->name('exam.store');
    Route::post('/exam/remove',[ExamController::class,'remove'])->name('exam.remove');

});

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use auth;
use App\Models\User;
use App\Models\Quizz;
use App\Models\Answer;
use App\Models\Result;
use App\Models\Question;
use Illuminate\Http\Request;

use Laravel\Ui\Presets\React;
use Illuminate\Support\Facades\DB;

class ExamController extends Controller
{
    public function create()
    {
        return view('backend.exam.create');
    }
    public function store(Request $request)
    {
        // dd($request->all());
       $quizz=Quizz::find($request->quizz_id);
       $quizz->users()->syncWithoutDetaching($request->user_id);

        return back()->with('success','Exam is assigned');
    }
    public function index()
    {
        return view('backend.exam.index',[
            'quizzs'=>Quizz::get()
        ]);
    }
    public function questions(Quizz $quizz)
    {
        // dd($quizz->questions);
        return view('backend.exam.question',[
            'questions'=> $quizz->questions
        ]);
    }
    public function remove(Request $request)
    {
       $userid=$request->get('user_id');
       $quizzid=$request->get('quizz_id');
       
       $exam=Quizz::find($quizzid);
       $result=Result::where('quizz_id',$quizzid)->where('user_id',$userid)->exits();

       if($result){
        return back()->with('error',"Cannot Remove Exam. Students Are Already registered to tgis. ");
    
       }
       $exam->users()->detach($userid);

       return back()->with('error',"Exam is removed.");
    }

    public function startQuizz(Quizz $quizz)
    {
        $question=Question::where('quizz_id',$quizz->id)->with('answers')->get();
        $time=Quizz::where('id',$quizz->id)->value('minutes');
        // dd($time);
        $authuser=auth()->user()->id;

        $userHasAissnged=DB::table('quizz_users')->where('user_id',$authuser)->where('quizz_id',$quizz->id)
                ->exists();
        if(!$userHasAissnged){
            return redirect('/home')->with("info",'This user is not assigned to the quizz');
        }
       
        $hasAnswered=DB::table('results')->where(['user_id'=>$authuser,'quizz_id'=>$quizz->id])->exists();
        if($hasAnswered){
            return  redirect('/home')->with('info',"This user has already answered this quizz");
        }

        
            return view('backend.exam.start',compact('quizz','question','time','hasAnswered'));

        
    
}
    public function register(Request $request)
    {
        $quizzid=$request['quizzid'];
        $questionid=$request['questionid'];
        $answerid=$request['answerid'];
        $authuser=auth()->user();

        Result::updateOrCreate([
            'user_id'=> $authuser->id,
            'question_id'=>$questionid,
            'quizz_id'=>$quizzid
        ],
        ['answer_id'=>$answerid]
    );
    }
    public function showresult(User $user,Quizz $quizz)
    {
        // questions  data
        $result = DB::table('quizz_users')->where('user_id', $user->id)->where('quizz_id', $quizz->id)->pluck('quizz_id');
        $questionWithAnswers = Question::wherein('quizz_id', $result)->with('answers')->get();
       

        // get the answer id from the result table 
        // increase if correct
        // return only correct answers


return $questionWithAnswers;
    //     $resultids=[];
    //    $result=DB::table('quizz_users')->where('user_id',$user->id)->where('quizz_id',$quizz->id)->pluck('quizz_id');
    //    $question=Question::wherein('quizz_id',$result)->get();
    //                 // retieving the correct answer
    //     $questions=$quizz->questions;
    //     $userResult=Answer::where('id', $question->id)->get();
        $marks=0;
        foreach($questionWithAnswers->answers as $correctanswer){
            // dd($correctanswer->is_correct);
            if($correctanswer->is_correct==1){
                $marks++;
            }
        }
        dd($result);

        return view('backend.exam.result',compact('quizz','questions','userResult','marks'));
    }
}

resources/views/backend/exam/create.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Assigning Exam to students
                    
                </h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('exam.store')}}"  method="POST">
                    @csrf 

                <div class="control-group">
                    <label for="">Choose Quizz</label>
                    <div class="controls">
                       <select name="quizz_id" id="" class="span8">
                            @foreach (App\Models\Quizz::all() as $item)
                       <option value="{{$item->id}}">{{$item->name}}</option>  
                            @endforeach

                       </select>
                    </div>

                    @error('quizz_id')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror


                <div class="control-group">
                    <label for="">Choose Users</label>
                    <div class="controls">
                       <select name="user_id" id="" class="span8">
                            @foreach (App\Models\User::all() as $user)
                       <option value="{{$user->id}}">{{$user->name}}</option>  
                            @endforeach

                       </select>
                    </div>

                    @error('user_id')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                   
                    
                    
                    
                    <button type="submit" class="btn btn-success"> Submit</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/exam/index.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    
    @if (Session::has('error'))
    <div class="alert alert-danger">
        
        {{Session::get('error')}}</div>

    @endif
    
    <div class="module">
        <div class="module-title">
           <h3>All Exams</h3>
        </div>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Quizz</th>
                <th>User Name</th>
                <th>Action</th>
               
            </tr>
        </thead>
        <tbody>
            @forelse ($quizzs as $key=>$quizz)
           @forelse ($quizz->users as $user)
               
         
                
             <tr>
                <td>{{$key+1}}</td>
                <td>{{$quizz->name}}</td>
                <td>{{$user->name}}</td>
                <td>
                       <a href="{{route('exam.question',[$quizz->id])}}">View Questions</a>

                   <form action="{{route('exam.remove')}}" method="POST">
                    @csrf

                    <input type="hidden" name="user_id" value="{{$user->id}}">
                    <input type="hidden" name="quizz_id" value="{{$quizz->id}}">

                    <button type="submit" > Delete</button>
                </form>
            
            </td>
             
                </tr>
                @empty
                <p>there are no exams yet.</p>
                @endforelse

               @empty
            @endforelse
        </tbody>
    </table>
</div>
</div>

@endsection

resources/views/backend/exam/question.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('error'))
        <div class="alert alert-danger">
            
            {{Session::get('error')}}</div>

        @endif
        @forelse ($questions as $item)
        <div class="module">
            <div class="module-title">
                <h3>{{ $item->quizz->name}}</h3>
                <h4>{{ $item->quizz->desc}}</h4>
                <h4>{{ $item->question}}</h4>
              <div class="module-body">
              <p>Given Minutes-{{$item->quizz->minutes}}</p>
              @forelse ($item->answers as $answer)
                  <p>{{$answer->answer}}
                    @if ($answer->is_correct==1)
                    <input type="checkbox" checked> <span class="badge badge-success">Correct Answer</span>
                    @else
                    <input type="checkbox" >
                    @endif
                </p>
                @empty
                <p>there is no answers set.</p>
              @endforelse
            </div> 

       
            {{-- <a href="{{route('question.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
        <form action="{{route('question.destroy',[$item->id])}}" method="POST">
            @csrf
            @method('delete')

            <button type="submit" class="btn btn-danger">delete</button>
        </form>     --}}
        </div>
        </div>
        @empty
        <p>there is no questions for this quizz</p>
            
        @endforelse 
        
       
            
    </div>
    {{-- <div class="pagination">
        {{ $questions->links() }}

    </div> --}}

</div>

@endsection

resources/views/backend/exam/result.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
 
   <div class="card">
       <div class="card-header text-uppercase">
           {{$quizz->name}}
          Marks {{$marks}} of {{$userResult->count()}}
       </div>
       <div class="card-body">
           @foreach ($questions  as $key=>$question)
                  <h3>{{$question->question}}</h3>
                    @foreach ($question->answers as $answer)
                   
                        <p>{{$answer->answer}}
                            @if ($answer->is_correct==1)
                            <span class="text-success">Correct Answer</span>
                            @endif
                            {{-- @if ($userResult[$key]->id==$answer->id)
                            
                                <span class="text-success">V</span>
                            @endif --}}
                        </p>
                    @endforeach
           @endforeach
           
       </div>
   </div>
      
</div>
@endsection

resources/views/backend/exam/start.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
        
    <div class="container">
        @if (Session::has('info'))
        <div class="alert alert-success">
            
            {{Session::get('info')}}</div>

        @endif
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8 ">
            <div class="container">
              

                
<question-component
            :time="{{$time}}"
            :question="{{$question}}"
            :quizzdata="{{$quizz}}"
></question-component>
                  
              
                      
                  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection