routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ExamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\QuizzController;
use App\Http\Controllers\QuestionController;
use Illuminate\Routing\Route as RoutingRoute;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    'register'=>false,
    'reset'=>false,
    'verify'=>false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('start/quizz/{quizz}',[ExamController::class,'startQuizz'])->name('quizz.enter');
Route::post('/result/create',[ExamController::class,'register']);
Route::get('/result/user/{user}/quizz/{quizz}',[ExamController::class,'showresult'])->name('show.result');
Route::group(['middleware' => 'admin'], function () {
    Route::get('/', function () {
        return view('admin.index');
    });
    Route::resource('quizz', QuizzController::class);
    Route::resource('question', QuestionController::class);
    Route::resource('user', UserController::class);
    Route::get('/exam/create',[ExamController::class,'create']);
    Route::get('/exam',[ExamController::class,'index']);
    Route::get('/exam/quizz/{quizz}',[ExamController::class,'questions'])->name('exam.question');
    Route::post('/exam/create',[ExamController::class,'store'])->name('exam.store');
    Route::post('/exam/remove',[ExamController::class,'remove'])->name('exam.remove');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','visible_password','occupation','phone','address','is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function storeUser($data)    
    {
        $data['visible_password']=$data['password'];
        $data['is_admin']=0;
        $data['password']=bcrypt($data['password']);
        // $data['email']=$data['mail'];
        return User::create($data);
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       return view('backend.user.index',[
           'users'=>User::latest()->paginate(20)
       ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    // dd($request->all());

        $this->validate($request,[
            'name'=>'required',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:3',
           
        ]);
            $user=(new User)->storeUser($request->all());

            return back()->with('success','User added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return 
       view('backend.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,User $user)
    {
      $data=  $this->validate($request,[
            'name'=>'required',
            'email'=>['required','email',
            Rule::unique('users')->ignore($user->email, 'email')
        ],
            'password'=>'required|min:3',

        ]);
        $data['visible_password']=$data['password'];
        $data['is_admin']=0;
        $data['password']=bcrypt($data['password']);
        $user->update($data);

        return redirect()->route('user.index')->with('success',"User Information Updated!");
        // dd($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return back();
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Registration Of Users</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('user.store')}}"  method="POST">
                    @csrf 

                <div class="control-group">
                    <label for="">User Name</label>
                    <div class="controls">
                        <input type="text" name="name" class="span8" placeholder="Please enter name">

                    </div>

                    @error('name')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">E-mail</label>
                    <div class="controls">
                        <input type="text" name="email" class="span8" placeholder="Please enter quizz"
                            value="{{old('email')}}"
                        >
                    </div>
                  
                    @error('email')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    
                    <label for="">password</label>
                    <div class="controls">
                        <input type="text" name="password" class="span8"                            value="{{old('email')}}"
                                value="{{old('email')}}"
                                placeholder="Please enter quizz">

                    </div>
                    @error('password')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    
                    <label for="">Occupation</label>
                    <div class="controls">
                        <input type="text" name="occupation" class="span8" placeholder="Please enter quizz">

                    </div>
                    @error('occupation')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    <label for="">Address</label>
                    <div class="controls">
                        <input type="text" name="address" class="span8" placeholder="Please enter quizz">

                    </div>
                    @error('address')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    
                    <label for="">Phone</label>
                    <div class="controls">
                        <input type="text" name="phone" class="span8" placeholder="Please enter quizz">

                    </div>
                    @error('phone')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  

                    <button type="submit" class="btn btn-success"> Submit</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    <div class="content">
        @if (Session::has('success'))
        <div class="alert alert-success">
            
            {{Session::get('success')}}</div>

        @endif
        <div class="module">
            <div class="module-name">
                <h3>Edit Of Users</h3>
            </div>
        
            <div class="module-body">
                <form action="{{route('user.update',[$user->id])}}"  method="POST">
                    @csrf 

                    @method('PUT')

                <div class="control-group">
                    <label for="">User Name</label>
                    <div class="controls">
                        <input type="text" name="name" class="span8" value="{{$user->name}}">

                    </div>

                    @error('name')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror

                    <label for="">E-mail</label>
                    <div class="controls">
                        <input type="text" name="email" class="span8" value="{{$user->email}}"
                            value="{{old('email')}}"
                        >
                    </div>
                  
                    @error('email')
                    <span class="invalid-feedback">
                        {{$message}}
                    </span>
                    @enderror
                    
                    <label for="">password</label>
                    <div class="controls">
                        <input type="text" name="password" class="span8"                            value="{{old('email')}}"
                               
                                placeholder="Please enter quizz">

                    </div>
                    @error('password')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    
                    <label for="">Occupation</label>
                    <div class="controls">
                        <input type="text" name="occupation" class="span8" value="{{$user->occupation}}">

                    </div>
                    @error('occupation')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    <label for="">Address</label>
                    <div class="controls">
                        <input type="text" name="address" class="span8" value="{{$user->address}}">

                    </div>
                    @error('address')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  
                    
                    <label for="">Phone</label>
                    <div class="controls">
                        <input type="text" name="phone" class="span8"   value="{{$user->phone}}"/>                    

                    </div>
                    @error('phone')
                    <span class="invalid-feedback">
                      
                        {{$message}}
                         {{-- @endforeach --}}
                    </span>
                    @enderror  

                    <button type="submit" class="btn btn-success"> Update</button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

@endsection

resources/views/backend/user/index.blade.php
@extends('backend.master')

@section('content')
<div class="span9">
    @if (Session::has('success'))
    <div class="alert alert-success">
        
        {{Session::get('success')}}</div>

    @endif
    @if (Session::has('error'))
    <div class="alert alert-danger">
        
        {{Session::get('error')}}</div>

    @endif
    <div class="module">
        <div class="module-title">
           <h3>All Users</h3>
        </div>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>E-mail</th>
                <th>Occupation</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($users as $key=>$user)
                <tr>
                <td>{{$key+1}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->occupation}}</td>
                <td>{{$user->address}}</td>
                <td>{{$user->phone}}</td>

                <td>{{$user->created_at}}</td>
                <td>{{$user->updated_at}}</td>
                <td>
                <a href="{{route('user.edit',[$user->id])}}" class="btn btn-primary">Edit</a>
                <form action="{{route('user.destroy',[$user->id])}}" method="POST">
                    @csrf
                    @method('delete')
                    <td>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </td>  
                </form>
            </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6">There are no Users yet.</td>                    
                </tr>
                
            @endforelse
        </tbody>
    </table>
</div>
</div>

@endsection